# Generated by Django 3.0.3 on 2020-02-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablero',
            old_name='nombre',
            new_name='creartablero',
        ),
    ]
